---
abstract: 'use sub attributes to specify which methods want modifiers'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Sub::Talisman: '0.002'
  Test::More: '0.61'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Moose::Meta::Class::__ANON__::SERIAL::11 version , CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-ModifyTaggedMethods
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  MooseX::ModifyTaggedMethods:
    file: lib/MooseX/ModifyTaggedMethods.pm
    version: '0.004'
requires:
  Moose: '2.00'
  MooseX::RoleQR: '0.003'
  match::simple: '0.004'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/MooseX-ModifyTaggedMethods/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-ModifyTaggedMethods
  homepage: https://metacpan.org/release/MooseX-ModifyTaggedMethods
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-moosex-modifytaggedmethods.git
version: '0.004'
