---
abstract: 'use sub attributes to specify which methods want modifiers'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Sub::Talisman: 0.002
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooseX::ModifyTaggedMethods
name: MooseX-ModifyTaggedMethods
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moose: 2.00
  MooseX::RoleQR: 0.003
  match::simple: 0.004
  perl: 5.8.3
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-ModifyTaggedMethods
  homepage: https://metacpan.org/release/MooseX-ModifyTaggedMethods
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-moosex-modifytaggedmethods
version: 0.003
